### ISSUE TITLE
Uncaught TypeError: editor.getSelections is not a function

### ISSUE THREAD

**Issue by Reck1501** [FPtje/linter-glualint#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-glualint](https://github.com/FPtje/linter-glualint) package 0.7.0

### Stack Trace

Uncaught TypeError: editor.getSelections is not a function

```
At C:\Users\Thomas\.atom\packages\linter-glualint\lib\init.coffee:59

TypeError: editor.getSelections is not a function
    at Object.prettyprint (/packages/linter-glualint/lib/init.coffee:59:25)
    at /packages/linter-glualint/lib/init.coffee:23:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:1300:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:58.3.0 linter-glualint:prettyprint (input.hidden-input)
     -3:54 core:undo (input.hidden-input)
     -3:53.2.0 core:redo (input.hidden-input)
  2x -3:24.9.0 core:backspace (input.hidden-input)
  2x -2:58.6.0 core:select-all (input.hidden-input)
     -2:38.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -2:11.9.0 welcome:show (input.hidden-input)
     -2:04.8.0 core:confirm (input.hidden-input)
     -1:07.5.0 core:select-all (input.hidden-input)
     -1:05.4.0 core:confirm (input.hidden-input)
     -0:13.8.0 linter-glualint:prettyprint (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
busy-signal 1.4.1 
glua-autocomplete 0.2.2 
intentions 1.1.2 
language-gmod-lua 0.4.0 
linter 2.1.4 
linter-glualint 0.7.0 
linter-ui-default 1.6.0 
```

**Comment by FPtje** [comment]
This error seems to be for an older version of the plugin. Please update.
