### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by dan2735** [FPtje/linter-glualint#7]
This is thrown when I first open Atom:

`[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter-glualint](https://github.com/FPtje/linter-glualint) package, v0.5.1
### Stack Trace

Uncaught TypeError: XRegExp is not a function

```
At /C:/Users/Daniel-/.atom/packages/linter-glualint/lib/init.coffee:125

TypeError: XRegExp is not a function
    at infoErrors (file:///C:/Users/Daniel-/.atom/packages/linter-glualint/lib/init.coffee:80:11)
    at BufferedProcess.exit (file:///C:/Users/Daniel-/.atom/packages/linter-glualint/lib/init.coffee:109:23)
    at triggerExitCallback (C:\Users\Daniel-\AppData\Local\atom\app-1.5.4\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\Daniel-\AppData\Local\atom\app-1.5.4\resources\app.asar\src\buffered-process.js:220:18
    at Socket.<anonymous> (C:\Users\Daniel-\AppData\Local\atom\app-1.5.4\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "linter-glualint": {}
}
```
### Installed Packages

``` coffee
# User
glua-autocomplete, v0.2.0
language-gmod-lua, v0.4.0
linter, v1.11.3
linter-glualint, v0.5.1

# Dev
No dev packages
```

`

**Comment by FPtje** [comment]
Could you try installing xregexp through npm? I don't see why that function shouldn't work. Xregexp's API doesn't seem to have changed.

**Comment by FPtje** [comment]
`npm install xregexp`

**Comment by dan2735** [comment]
I'm sorry I'm not quite sure how to do that. npm, apm, and  atom do not show up as valid cmd commands. I just got atom and am a bit new to using it fully.
